name: payroll deployement

on:
  push:
    branches:
      - main
      #branches-ignore:
      #- '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MIKRO_STG_HOST }}
          username: ${{ secrets.MIKRO_STG_USER }}
          port: ${{ secrets.MIKRO_STG_PORT }}
          password: ${{ secrets.MIKRO_STG_HOST_PASS }}
          #KEY: ${{ secrets.MIKRO_STG_SSH_KEY }}
          source: "."
          target: "/var/www/blackcoder"

      - name: executing laravel deployement commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MIKRO_STG_HOST }}
          username: ${{ secrets.MIKRO_STG_USER }}
          port: ${{ secrets.MIKRO_STG_PORT }}
          password: ${{ secrets.MIKRO_STG_HOST_PASS }}
          #KEY: ${{ secrets.MIKRO_STG_SSH_KEY }}
          script: |
            # cd /var/www/blackcoder
            cd /var/www/blackcoder
            echo "creating env file...."
            php -r "file_exists('.env') || copy('.env.example', '.env');"
            echo "executing composer install...."
            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            echo "Generating key..."
            php artisan key:generate
            echo "Granting directory permissions..."
            chmod -R 777 storage bootstrap/cache
            echo "running migration"
            php artisan migrate
            echo "run seed"
            php artisan db:seed
            echo "finally unit testing..."
            vendor/bin/phpunit
            echo "executing yarn command"
            echo  yarn && yarn run prod
            echo "done...."
