name: payroll production deployement

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          port: ${{ secrets.PROD_PORT }}
          key: ${{ secrets.PROD_SSH_KEY }}
          source: "."
          target: "/home/azureuser/simplix"
      - run: |
          rm -rf .git
          ls -la


      - name: executing laravel deployement commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          port: ${{ secrets.PROD_PORT }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            echo "removing .git file"
            rm -rf /home/azureuser/simplix/.git
            echo "transferring files to application server"
            scp -i ${{secrets.PROD_APP_KEY_PATH}} -r /home/azureuser/simplix ${{secrets.PROD_USER}}@${{secrets.PROD_APP_SERVER_HOST}}:/home/azureuser
            echo "cleaning direcory"
            ssh -i ${{secrets.PROD_APP_KEY_PATH}} ${{secrets.PROD_USER}}@${{secrets.PROD_APP_SERVER_HOST}} "cd /var/www/simplix && sudo rm -rf public app bootstrap config database resources routes tests composer.json package.json phpunit.xml server.php webpack.mix.js dump.rdb artisan .github"
            echo "transfering files to hosting directory..."
            ssh -i ${{secrets.PROD_APP_KEY_PATH}} ${{secrets.PROD_USER}}@${{secrets.PROD_APP_SERVER_HOST}} "sudo mv -f -v /home/azureuser/simplix/* /var/www/simplix"
            #echo "login to app server"
            #echo "creating env file...."
            #ssh -i ${{secrets.PROD_APP_KEY_PATH}} ${{secrets.PROD_USER}}@${{secrets.PROD_APP_SERVER_HOST}} 'cd /var/www/simplix && sudo /usr/bin/php -r "file_exists('.env') || copy('.env.example', '.env');"'
            ssh -i ${{secrets.PROD_APP_KEY_PATH}} ${{secrets.PROD_USER}}@${{secrets.PROD_APP_SERVER_HOST}} "echo ls /var/www"
            echo "executing composer install...."
            ssh -i ${{secrets.PROD_APP_KEY_PATH}} ${{secrets.PROD_USER}}@${{secrets.PROD_APP_SERVER_HOST}} "cd /var/www/simplix && sudo /usr/local/bin/composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs"
            echo "Generating key..."
            ssh -i ${{secrets.PROD_APP_KEY_PATH}} ${{secrets.PROD_USER}}@${{secrets.PROD_APP_SERVER_HOST}} "cd /var/www/simplix && sudo /usr/bin/php artisan key:generate"
            ssh -i ${{secrets.PROD_APP_KEY_PATH}} ${{secrets.PROD_USER}}@${{secrets.PROD_APP_SERVER_HOST}} "cd /var/www/simplix && sudo /usr/bin/php artisan cache:clear"
            echo "Granting directory permissions..."
            ssh -i ${{secrets.PROD_APP_KEY_PATH}} ${{secrets.PROD_USER}}@${{secrets.PROD_APP_SERVER_HOST}} "cd /var/www/simplix && sudo chmod -R 777 storage bootstrap/cache"
            echo "running migration"
            ssh -i ${{secrets.PROD_APP_KEY_PATH}} ${{secrets.PROD_USER}}@${{secrets.PROD_APP_SERVER_HOST}} "cd /var/www/simplix && sudo /usr/bin/php artisan migrate"
            echo "running Storage link"
            ssh -i ${{secrets.PROD_APP_KEY_PATH}} ${{secrets.PROD_USER}}@${{secrets.PROD_APP_SERVER_HOST}} "cd /var/www/simplix && sudo /usr/bin/php artisan storage:link"
            echo "done...."
